#remote_theme: jekyll/minima # force remote download to get the most recent version, which has skins
remote-theme: rahil627/minima-custom # i won't ever rememeber to update my forked version :(
#remote_theme: rahil627/ultra # nice, but no dynamic nav bar :(
#remote_theme: pages-themes/primer
#remote_theme: pages-themes/minimal
#remote_theme: poole/lanyon

title: conceptual fighting #: the art and way of fighting games #fighting game anarchy: the art and way of fighting games
#description: # fetches this from github repo's about section

# theme specific stuff
minima:
  skin: light #default

#author:
#  name: a <a href="https://willowolf.com">willowolf</a> of <a href="https://rathewolf.com">rathewolf</a> #can't add html to this because it is unformatted for seo use
#  email: '' # error if i provide name but not e-mail?
    
footer:
  left: a <a href="https://willowolf.com">willowolf</a> of <a href="https://rathewolf.com">rathewolf</a>
#  center: 'footer center'
#  right: 'footer right

# messisg with something
#defaults:
#  -
#    scope:
#      path: "" # an empty string here means all files in the project
#    values:
#      layout: "default" # "toc"
