title: the way of fighting games
author:
  name: rathewolf
  #email: your-email@domain.com
#description: fetch this from the github repo's about section
  
# theme: jekyll-theme-midnight
remote_theme: jekyll/minima # force remote download to get the most recent version, which has skins
minima:
  skin: dark

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default" # "toc"
