title: fighting willowolf: the art and way of fighting games
#description: # fetches this from github repo's about section
  
# theme: jekyll-theme-midnight
remote_theme: jekyll/minima # force remote download to get the most recent version, which has skins

# theme specific stuff
minima:
  skin: dark
  
  author:
    name: a <a href="https://willowolf.com">willowolf</a> of <a href="https://rathewolf.com">rathewolf</a>
    #email: your-email@domain.com


# messisg with something
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default" # "toc"
