#remote_theme: jekyll/minima # force remote download to get the most recent version, which has skins
remote_theme: rahil627/minima-custom-jekyll-theme # i won't ever rememeber to update my forked version :(
#remote_theme: rahil627/ultra # nice, but no dynamic nav bar :(
#remote_theme: pages-themes/primer # todo: worth trying for a barebones theme
#remote_theme: poole/lanyon

title: "conceptual fighting: the art, design, 'n way of fighting games" #fighting game anarchy: the art and way of fighting games
title-short: 'conceptual fighting'
#description: # fetches this from github repo's about section

# theme specific stuff
#minima:
  #skin: classic #default

#author:
#  name: a <a href="https://willowolf.com">willowolf</a> of <a href="https://rathewolf.com">rathewolf</a> #can't add html to this because it is unformatted for seo use
#  email: '' # error if i provide name but not e-mail?
    
footer:
  left: 'a <a href="https://willowolf.com">willowolf</a> of <a href="https://rathewolf.com">rathewolf</a>'

# messing with jekyll / testing
#defaults:
#  -
#    scope:
#      path: "" # an empty string here means all files in the project
#    values:
#      layout: "default" # "toc"
