remote_theme: rahil627/minima-customized # i won't ever rememeber to update my forked version :(
#remote_theme: rahil627/ultra # nice, but no dynamic nav bar :(

title: "conceptual fighting: the dao of fighting games"
#description: # fetches this from github repo's about section

# theme specific stuff
minima:
  skin: classic #default black on white

#author: #appears in the footer :/
  #name: rahil627 aka rathewolf #used by seo? #can't add html to this because it is unformatted for seo use
  #email: '' # error if i provide a name without an e-mail?
    
# custom stuff
title-short: 'conceptual fighting'
text-align: center
footer:
  left: 'a <a href="https://willowolf.com">willowolf</a> of <a href="https://rathewolf.com">rathewolf</a>'

# messing with jekyll / testing
#defaults:
#  -
#    scope:
#      path: "" # an empty string here means all files in the project
#    values:
#      layout: "default" # "toc"


