remote_theme: jekyll/minima # force remote download to get the most recent version, which has skins
#remote_theme: rahil627/ultra # nice, but no dynamic nav bar :(
#remote_theme: pages-themes/primer
#remote_theme: pages-themes/minimal
#remote_theme: poole/lanyon

title: "conceptual fighting" #: the art and way of fighting games #fighting game anarchy: the art and way of fighting games
#description: # fetches this from github repo's about section

# theme specific stuff
author:
  name: a <a href="https://willowolf.com">willowolf</a> of <a href="https://rathewolf.com">rathewolf</a>
  email: '' # error if i provide name but not e-mail?
    


# messisg with something
#defaults:
#  -
#    scope:
#      path: "" # an empty string here means all files in the project
#    values:
#      layout: "default" # "toc"
