# theme: jekyll-theme-midnight
remote_theme: minima # force remote download to get the most recent version, which has skins

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default" # "toc"
