#remote_theme: jekyll/minima # force remote download to get the most recent version, which has skins
remote_theme: rahil627/minima-custom-jekyll-theme # i won't ever rememeber to update my forked version :(
#remote_theme: rahil627/ultra # nice, but no dynamic nav bar :(

title: "conceptual fighting: the way of fighting games"
#description: # fetches this from github repo's about section

# theme specific stuff
minima:
  plugins:
   - jekyll-seo-tag
  
  #skin: classic #default black on white

#author:
  #name: rahil627 #used by seo? #can't add html to this because it is unformatted for seo use
  #email: '' # error if i provide a name without an e-mail?
    
# custom stuff
title-short: 'conceptual fighting'
text-align: center
footer:
  left: 'a <a href="https://willowolf.com">willowolf</a> of <a href="https://rathewolf.com">rathewolf</a>'

# messing with jekyll / testing
#defaults:
#  -
#    scope:
#      path: "" # an empty string here means all files in the project
#    values:
#      layout: "default" # "toc"
